networks:
  phlare:


services:
  phlare:
    image: grafana/phlare:0.1.0@sha256:a73b5b85512b528ea18d07b5d6266026af4a52eae9afb1c4b795b2ecfe70ab87
    ports:
      - "4100:4100"
    entrypoint:
      - /bin/sh
      - -euc
      - |
        cat > /tmp/config.yaml <<EOF
        scrape_configs:
          - job_name: "phlare"
            scrape_interval: "15s"
            static_configs:
              - targets: ["phlare:4100"]
          - job_name: "grafana"
            scrape_interval: "15s"
            static_configs:
              - targets: ["grafana:6060"]
          - job_name: "cp-rust"
            scrape_interval: "15s"
            static_configs:
              - targets: ["rust:3000"]
            profiling_config:
              pprof_config:
                block: {enabled: false}
                goroutine: {enabled: false}
                memory: {enabled: false}
                mutex: {enabled: false}
          - job_name: "cp-python"
            scrape_interval: "15s"
            static_configs:
              - targets: ["python:8081"]
            profiling_config:
              pprof_config:
                block: {enabled: false}
                goroutine: {enabled: false}
                mutex: {enabled: false}
        EOF

        exec phlare -config.file=/tmp/config.yaml
    volumes:
      - ./phlare.yaml:/etc/phlare/config.yaml
      - data:/data
    networks:
      - phlare

  grafana:
    image: aocenas/grafana:profiling-ds-2@sha256:34e6cf8c315c8efea3368cdadbc448d671f791df02a8dbb75f7376e323cb3dab
    ports:
      - "3000:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_DIAGNOSTICS_PROFILING_ENABLED=true
      - GF_DIAGNOSTICS_PROFILING_ADDR=0.0.0.0
      - GF_DIAGNOSTICS_PROFILING_PORT=6060
    volumes:
      - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasources.yml
    networks:
      - phlare

  rust:
    image: simonswine/cp-rust:0.1.0
    ports:
      - 8080:3000
    networks:
      - phlare

  python:
    image: simonswine/cp-python:0.1.0
    ports:
      - 8081:8081
    networks:
      - phlare

volumes:
  data:

# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
